### ISSUE TITLE
moving callbacks into similar service package

### ISSUE THREAD

**Issue by tonmoy71** [NerdCats/SwatKat#7]
Need to move the callbacks into their respective service package like
`swatkat.service.location.LocationService` 
`swatkat.service.location.LocationCallback`
@fahadwajed up to you :)

**Comment by fahadwajed** [comment]
oka

**Comment by fahadwajed** [comment]
done

**Comment by tonmoy71** [comment]
Did you push it? @fahadwajed

**Comment by tonmoy71** [comment]
@fahadwajed Please move the Login and Profile callback to their respective package.

**Comment by fahadwajed** [comment]
done and pushed.
